platform :ios, '9.0'

target 'to_dos' do
  
  use_frameworks!

  # Pods for to_dos
  pod 'RealmSwift'
  pod 'SwipeCellKit'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'
end
